name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.9"]
    defaults:
      run:
        shell: bash -l {0}
    name: Linux py ${{ matrix.python-version }} tests
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: molucn
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - run: |
          conda info
          pip install pytest
        name: set pythonpath
      - run: |
          echo "PYTHONPATH=/home/runner/work/molucn/molucn" >> $GITHUB_ENV
        name: test
      - run: |
          pytest --cov=molucn --cov-config=.coveragerc --cov-report=xml tests/
